Implement Graphical Representation of score and similar command
sdsmdg/bot pull request #27
Opened 2021-08-30 15:54 UTC by aman-singh7

fixes #22

2021-08-31 16:41 UTC, dev-ritik requested changes

2021-08-31 16:41 UTC, dev-ritik commented on README.md
> +REDIS_URL=redis://redis:6379
Make this change in a separate PR

2021-08-31 16:41 UTC, dev-ritik commented on package.json
> +    "follow-redirects": "1.13.0",
I don't think this is required

2021-08-31 16:41 UTC, dev-ritik commented on scripts/util.coffee
> +https = require('follow-redirects').http
I don't think this is required

2021-08-31 16:41 UTC, dev-ritik commented on scripts/graph-batch-score.coffee
> +            false
If this is the same parse function, don't write it again. Use the existing one

2021-08-31 16:41 UTC, dev-ritik commented on scripts/graph-batch-score.coffee
> +        Field
If this is the same scorefield function, don't write it again. Use the existing one

2021-08-31 16:41 UTC, dev-ritik commented on scripts/graph-batch-score.coffee
> +            user_name = []
Use the existing code don't re-write

2021-09-01 21:11 UTC, aman-singh7 commented
@dev-ritik committed those changes.

2021-09-05 07:42 UTC, dev-ritik requested changes

2021-09-05 07:42 UTC, dev-ritik commented on scripts/detailed-score.coffee
> -
Don't make unnecessary changes

2021-09-05 07:42 UTC, dev-ritik commented on scripts/detailed-score.coffee
> +
Don't make unnecessary changes

2021-10-03 06:56 UTC, dev-ritik approved these changes

2021-11-06 17:22 UTC, merged